spring:
  datasource:
    url: jdbc:mysql://34.87.140.46:3306/ManagementArea?useSSL=false
    username: root
    password: Ongart278612
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  mvc:
    log-request-details: true 
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB    
logging: 
  level:
    org:
      springframework:
        web: TRACE
      hibernate: INFO
  
server:
  port: 8080
  
file:
  upload-dir: D:/trackYouX/uploads
  
app:
  security:
    constants:
      expiration_time: 0 # 0*60*60*1000
      
images:
  blackguard: blackgroup.jpg
  profile: profile.jpg 
 
